/**
 * Intrinsic pixel dimensions for every image referenced by content.
 *
 * `next/image` needs real dimensions to reserve a box before the bytes arrive. The
 * migrated content cannot supply them: its `width` prop is a CSS string ("500px") that
 * carries no aspect ratio, and `height` appears on 6 images out of ~490. Without an
 * intrinsic ratio the browser cannot compute the height, so the page reflows as each image
 * loads.
 *
 * The manifest is generated by scripts/fetch-image-dimensions.ts and committed, so builds
 * need no network access. Re-run that script when content adds images.
 */

import manifest from './image-dimensions.json'

export interface Dimensions {
  w: number
  h: number
}

const dimensions: Record<string, Dimensions> = manifest

/**
 * Returns undefined for an image added to content since the manifest was last generated.
 * Callers degrade to an unsized image rather than failing the build — a missing entry
 * costs layout shift on one image, which is not worth breaking a deploy over.
 */
export function getDimensions(src: string): Dimensions | undefined {
  return dimensions[src]
}
