'use client'

import Image from 'next/image'
import Link from 'next/link'
import type { Locale } from '@/lib/permalink'
import { pagePermalink } from '@/lib/permalink'
import type { CarouselSlide } from '@/lib/schema'
import buttons from '../section-button.module.css'
import styles from './carousel.module.css'

/**
 * One hero slide.
 *
 * `isInitiallyActive` is a literal, not state: it has to be present in the exported HTML so the
 * first slide's text is visible and its animations start before any JavaScript runs. An effect
 * cannot do that — effects do not run during the static export pass.
 */
export function CarouselSlide({
  slide,
  locale,
  isInitiallyActive,
  ref,
}: {
  slide: CarouselSlide
  locale: Locale
  isInitiallyActive: boolean
  ref: React.Ref<HTMLDivElement>
}) {
  const title = slide.title[locale]

  return (
    <div ref={ref} className={styles.slide} data-active={isInitiallyActive ? 'true' : undefined}>
      {/*
        `fill` rather than width/height: these are `object-fit: cover` backdrops, so intrinsic
        dimensions are meaningless, and three of the four slide images have no entry in
        lib/image-dimensions.json — that manifest is generated by scanning content MDX, and
        these come from content/data. `fill` needs none.

        Only the first slide is `priority`; it is the page's LCP element. The other three are
        left at the default lazy — an earlier version marked them `eager`, which made Next emit
        a preload link for each, so four full-bleed heroes raced the one that actually matters
        and the LCP hint bought nothing. They sit just outside a clipped viewport, so browsers
        fetch them early on proximity anyway, and autoplay does not advance for 5s regardless.
      */}
      <Image
        src={slide.image}
        alt={slide.alt[locale]}
        fill
        sizes="100vw"
        className={styles.image}
        priority={isInitiallyActive}
      />

      <div className={styles.gradient} />

      <div className={styles.overlay}>
        {slide.href ? (
          <Link href={pagePermalink(slide.href, locale)} className={styles.link} title={title}>
            <h1>{title}</h1>
          </Link>
        ) : (
          <h1>{title}</h1>
        )}

        {/*
          The only dangerouslySetInnerHTML on the homepage, and it matches the source: these
          descriptions are authored as raw `<ul>` markup in data/carousel/*.yaml and rendered
          through Hugo's `safeHTML`. The content is repo-authored, not user input, and the
          schema documents the field as HTML rather than markdown.
        */}
        <div dangerouslySetInnerHTML={{ __html: slide.description[locale] }} />

        {/*
          Hugo hardcodes href="/contact" here with no locale branch, so the English homepage
          links to the French contact page. Fixed rather than ported — see docs/homepage-port.md.
        */}
        <Link
          href={pagePermalink('contact', locale)}
          className={`${buttons.outline} ${buttons.hero} ${styles.cta}`}
        >
          {slide.contactText[locale]}
        </Link>
      </div>
    </div>
  )
}
