'use client'

import Image from 'next/image'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useTranslations } from 'next-intl'
import { MAIN_MENU, resolveMenu } from '@/lib/nav-menu'
import { localeHref, type Locale } from '@/lib/permalink'
import { getSiteConfig } from '@/lib/site-config'
import { DropdownMenuItem } from './dropdown-menu-item'
import { BurgerIcon } from './icons'
import { LanguageSwitcher } from './language-switcher'
import { NavLink } from './nav-link'

/**
 * The site header: brand, main menu, language switcher, mobile toggle.
 *
 * A client component, because active state and the language switcher both need the current
 * path and `headers()` is a dynamic API that `output: 'export'` forbids. That costs nothing
 * in the exported HTML: Next renders each route's client tree during the export pass, so
 * `usePathname()` already returns the real path and every page ships with the correct link
 * highlighted before any hydration happens.
 *
 * Three pieces of Bootstrap JS are replaced here, all with less than they cost:
 *
 * - **collapse** — the mobile panel, now `navOpen`.
 * - **dropdown** — owned by `DropdownMenuItem`.
 * - **affix** (`data-spy="affix" data-offset-top="62"`) — the pinning itself was never the
 *   plugin's doing; `.navbar-affixed-top` is `position: sticky` in CSS. The plugin only
 *   toggled a class past 62px, which changed the background and added a shadow. A scroll
 *   listener setting `affixed` reproduces it exactly.
 */
export function SiteHeader({ locale }: { locale: Locale }) {
  const pathname = usePathname()
  const t = useTranslations('Nav')
  const site = getSiteConfig(locale)

  const [navOpen, setNavOpen] = useState(false)
  const [affixed, setAffixed] = useState(false)

  useEffect(() => {
    // Matches data-offset-top="62" on the Hugo header.
    let frame = 0
    function onScroll() {
      if (frame) return
      frame = requestAnimationFrame(() => {
        setAffixed(window.scrollY > 62)
        frame = 0
      })
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => {
      window.removeEventListener('scroll', onScroll)
      if (frame) cancelAnimationFrame(frame)
    }
  }, [])

  // Bootstrap's collapse left the panel open across navigations; with client-side routing
  // the panel would otherwise still be covering the page the visitor just asked for.
  // Adjusted during render rather than in an effect: React re-runs this component before
  // committing, so the panel is never painted open on the new route. An effect would
  // paint once, then close, and costs a second render pass to do it.
  const [renderedPath, setRenderedPath] = useState(pathname)
  if (renderedPath !== pathname) {
    setRenderedPath(pathname)
    setNavOpen(false)
  }

  const items = resolveMenu(MAIN_MENU, locale, pathname)

  return (
    <header
      className={[
        'sticky top-0 z-50 border-b border-white/6 backdrop-blur-navbar transition-colors duration-250',
        affixed ? 'bg-surface-nav-affixed shadow-navbar' : 'bg-surface-nav',
      ].join(' ')}
    >
      <div className="container flex flex-wrap items-center justify-between">
        <Link href={localeHref('/', locale)} className="flex items-center py-2.5">
          {/* Intrinsic size of the Cloudinary asset. Hardcoded rather than read from
              lib/image-dimensions.json: that manifest is generated by scanning content
              MDX, and the logo is chrome, not content. Routing it through next/image
              means the custom Cloudinary loader applies f_auto,q_auto,c_limit — the
              source ships the full 36 KB PNG to every page at every viewport. */}
          <Image
            src={site.logoSrc}
            alt={`${site.title} logo`}
            width={736}
            height={195}
            priority
            className="h-11 w-auto"
          />
          <span className="sr-only">
            {site.title} - {t('goToHomepage')}
          </span>
        </Link>

        <button
          type="button"
          aria-expanded={navOpen}
          aria-controls="navigation"
          onClick={() => setNavOpen((wasOpen) => !wasOpen)}
          className="border border-white/20 p-2.5 text-white/80 transition-colors hover:bg-white/10 sm:hidden"
        >
          <span className="sr-only">{t('toggleNavigation')}</span>
          <BurgerIcon />
        </button>

        <nav
          id="navigation"
          className={`${navOpen ? 'block' : 'hidden'} w-full sm:block sm:w-auto`}
        >
          <ul className="flex flex-col sm:flex-row sm:items-center">
            {items.map((item) =>
              item.children ? (
                <DropdownMenuItem key={item.id} item={item} pathname={pathname} />
              ) : (
                <li key={item.id}>
                  <NavLink href={item.href} active={item.active} linkProps={item.linkProps}>
                    {item.label}
                  </NavLink>
                </li>
              ),
            )}
            <li>
              <LanguageSwitcher
                locale={locale}
                pathname={pathname}
                label={t('switchLanguage')}
              />
            </li>
          </ul>
        </nav>
      </div>
    </header>
  )
}
